import { Request, Response } from "express";
import Site from "../model/Site";
import Event from "../model/Event";
import { AuthRequest } from "../middleware/auth";

// Get - fetch all the sites for logged user
export const getSites = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const sites = await Site.findAll({
            where: { userId: req.userId },
            order: [['createdAt', 'DESC']],

        });

        res.json(sites);

    }catch(error: unknown) {
        if(error instanceof Error) {
            res.status(500).json({message: error.message});
        }
    }
};

// Post - create a new site
export const createSite = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const {name, domain, timezone} = req.body;

        if(!name || !domain) {
            res.status(400).json({error: 'Name and Domain are required'});
            return;
        }

        // clean domain - remove http/https and trailing slash
        const cleanDomain = domain
            .replace(/^https?:\/\//, '')
            .replace(/\/$/, '')
            .toLowerCase();

        // check if domain is already registered by this user
        const exists = await Site.findOne({
            where: {domain: cleanDomain, userId: req.userId },
        });

        if(exists) {
            res.status(400).json({message: 'Domain already added'});
            return;
        }

        // siteId is auto-generated by Sequelize via UUIDV4
        const site = await Site.create({
            name,
            domain: cleanDomain,
            userId: req.userId!,
            timezone: timezone || 'UTC'
        });

        res.status(201).json(site);

    }catch(error: unknown) {
        if(error instanceof Error) {
            res.status(500).json({message: error.message});
        }
    }
};

// Get - get single site by siteId
export const getSite = async(req: AuthRequest, res: Response): Promise<void> => {
    try {
        const site = await Site.findOne({
            where: {
                siteId: req.params.siteId,
                userId: req.userId,
            },
        });

        if(!site) {
            res.status(404).json({message: 'Site not found'});
            return;
        }

        res.json(site);

    }catch(error: unknown) {
        if(error instanceof Error) {
            res.status(500).json({message: error.message});
        }
    }
};

// Put - update site name or timezone
export const updateSite = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const site = await Site.findOne({
            where: {
                id: req.params.id,
                userId: req.userId
            },
        });

        if(!site) {
            res.status(404).json({message: 'Site not Found'});
            return;
        }

        const { name, domain, timezone } = req.body;

        let cleanDomain: string | undefined;
        if (domain) {
            cleanDomain = domain
                .replace(/^https?:\/\//, '')
                .replace(/\/$/, '')
                .toLowerCase();

            const exists = await Site.findOne({
                where: { domain: cleanDomain, userId: req.userId },
            });

            if (exists && exists.id !== site.id) {
                res.status(400).json({message: 'Domain already added'});
                return;
            }
        }

        await site.update({
            name: name || site.name,
            domain: cleanDomain || site.domain,
            timezone: timezone || site.timezone,
        });

        res.json(site);

    }catch(error: unknown) {
        if(error instanceof Error) {
            res.status(500).json({message: error.message});
        }
    }
};

// Delete - delete site and all its events
export const deleteSite = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const site = await Site.findOne({
            where: {
                id: req.params.id,
                userId: req.userId,
            },
        });

        if(!site) {
            res.status(404).json({message: 'Site not found'});
            return;
        }
        
        // delete all events first before deleting site
        // explicitly deleting is safer and faster
        await Event.destroy({where: {siteId: site.siteId } });
        await site.destroy();

        res.json({message: 'Site deleted Successfully'});

    }catch(error: unknown){
        if(error instanceof Error) {
            res.status(500).json({message: error.message});
        }
    }
};

// Get - get SDK snippet for a site
export const getSnippet = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const site = await Site.findOne({
            where: {
                id: req.params.id,
                userId: req.userId,
            },
        });

        if(!site) {
            res.status(404).json({message: 'Site not found'});
            return;
        }

        // generate the script tag developers copy-paste
        const serverUrl = process.env.SERVER_URL || 'http://localhost:5000';

        const snippet = `<script src="${serverUrl}/sdk.js" data-site="${site.siteId}" defer></script>`;
        res.json({ snippet, siteId: site.siteId });

    }catch (error: unknown) {
        if(error instanceof Error) {
            res.status(500).json({message: error.message});
        }
    }
};
